--------------------------------------------------------
--  File created - Saturday-December-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EVENT_DATA
--------------------------------------------------------

  CREATE TABLE "QUAKE"."EVENT_DATA" 
   (	"EVENT_DATA_ID" VARCHAR2(100 CHAR) DEFAULT sys_guid(), 
	"FETCH_TIME" TIMESTAMP (3) DEFAULT systimestamp, 
	"TIME_FROM" VARCHAR2(25 CHAR), 
	"TIME_TO" VARCHAR2(25 CHAR), 
	"GEN_DATE" VARCHAR2(25 CHAR), 
	"FEED_URL" VARCHAR2(500 CHAR), 
	"TITLE" VARCHAR2(500 CHAR), 
	"FETCH_STATUS" VARCHAR2(100 CHAR), 
	"API" VARCHAR2(50 CHAR), 
	"EQ_COUNT" NUMBER, 
	"EVENT_DATATYPE" VARCHAR2(30 CHAR), 
	"EVENT_CLOB" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_DATA" 
 LOB ("EVENT_CLOB") STORE AS SECUREFILE "EVENT_DATA_CLOB"(
  TABLESPACE "EQ_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."EVENT_DATA_ID" IS 'EVENT_DATA_ID: Primary Key.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."FETCH_TIME" IS 'FETCH_TIME: Time of feed fetch.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."TIME_FROM" IS 'TIME_FROM: Starting time range of event_data set.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."TIME_TO" IS 'TIME_TO: Ending time range of event_data set.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."GEN_DATE" IS 'GEN_DATE (GENERATED): Time when the feed was most recently updated. Times are reported in milliseconds since the epoch.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."FEED_URL" IS 'FEED_URL (URL): Url of the feed.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."TITLE" IS 'TITLE: The title of the feed.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."FETCH_STATUS" IS 'FETCH_STATUS (STATUS): HTTP status code of response.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."API" IS 'API: Version of API that generated feed.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."EQ_COUNT" IS 'EQ_COUNT (COUNT): Number of earthquakes in feed.';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."EVENT_DATATYPE" IS 'EVENT_DATATYPE: Structure of datatype stored in EVENT_CLOB column. Types: GEOJSON, XML, QUAKEML (XML), XML, KML (Google Format), TEXT ("|" delimited).';
   COMMENT ON COLUMN "QUAKE"."EVENT_DATA"."EVENT_CLOB" IS 'EVENT_DATA: CLOB column for storing the feed data as an object.';
   COMMENT ON TABLE "QUAKE"."EVENT_DATA"  IS 'EVENT_DATA: Stores feed fetch rows and associated metadata from (http://earthquake.usgs.gov)';
--------------------------------------------------------
--  DDL for Index EVENT_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUAKE"."EVENT_DATA_PK" ON "QUAKE"."EVENT_DATA" ("EVENT_DATA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_IX" ;
--------------------------------------------------------
--  Constraints for Table EVENT_DATA
--------------------------------------------------------

  ALTER TABLE "QUAKE"."EVENT_DATA" ADD CONSTRAINT "EVENT_CLOB_CK" CHECK (event_clob is json (strict)) ENABLE;
  ALTER TABLE "QUAKE"."EVENT_DATA" ADD CONSTRAINT "EVENT_DATA_PK" PRIMARY KEY ("EVENT_DATA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_IX"  ENABLE;
