--------------------------------------------------------
--  File created - Saturday-December-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EVENT_MOON_RELATION
--------------------------------------------------------

  CREATE TABLE "QUAKE"."EVENT_MOON_RELATION" 
   (	"REL_ID" VARCHAR2(100 CHAR), 
	"EVENT_DATA_ID" VARCHAR2(50 CHAR), 
	"EQ_EVENT_ID" VARCHAR2(50 CHAR), 
	"USGS_ID" VARCHAR2(50 CHAR), 
	"EQ_EVENT_TIME" DATE, 
	"MOON_DIST" NUMBER, 
	"MOON_DECL" NUMBER, 
	"MOON_RA" NUMBER, 
	"LOAD_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_DATA" ;
--------------------------------------------------------
--  DDL for Index EV_MOON_REL_USGS_ID_IX2
--------------------------------------------------------

  CREATE INDEX "QUAKE"."EV_MOON_REL_USGS_ID_IX2" ON "QUAKE"."EVENT_MOON_RELATION" ("USGS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_IX" ;
--------------------------------------------------------
--  DDL for Index EV_MOON_REL_EV_TIME_IX3
--------------------------------------------------------

  CREATE INDEX "QUAKE"."EV_MOON_REL_EV_TIME_IX3" ON "QUAKE"."EVENT_MOON_RELATION" ("EQ_EVENT_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_IX" ;
--------------------------------------------------------
--  Constraints for Table EVENT_MOON_RELATION
--------------------------------------------------------

  ALTER TABLE "QUAKE"."EVENT_MOON_RELATION" MODIFY ("REL_ID" NOT NULL ENABLE);
