--------------------------------------------------------
--  File created - Saturday-December-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LUNAR_RELATION
--------------------------------------------------------

  CREATE TABLE "QUAKE"."LUNAR_RELATION" 
   (	"REL_ID" VARCHAR2(100 CHAR), 
	"EVENT_DATA_ID" VARCHAR2(50 CHAR), 
	"EQ_EVENT_ID" NUMBER(*,0), 
	"USGS_ID" VARCHAR2(50 CHAR), 
	"EQ_EV_TIME" DATE, 
	"EQ_EV_MTH" NUMBER, 
	"EQ_EV_YR" NUMBER, 
	"MOON_DIST" NUMBER, 
	"MOON_DECL" NUMBER, 
	"MOON_RA" NUMBER, 
	"LOAD_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_DATA" ;
--------------------------------------------------------
--  DDL for Index LUNAR_REL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUAKE"."LUNAR_REL_PK" ON "QUAKE"."LUNAR_RELATION" ("REL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_IX" ;
--------------------------------------------------------
--  DDL for Index LUNAR_REL_EV_MTH
--------------------------------------------------------

  CREATE INDEX "QUAKE"."LUNAR_REL_EV_MTH" ON "QUAKE"."LUNAR_RELATION" ("EQ_EV_MTH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_IX" ;
--------------------------------------------------------
--  DDL for Index LUNAR_REL_EV_YR
--------------------------------------------------------

  CREATE INDEX "QUAKE"."LUNAR_REL_EV_YR" ON "QUAKE"."LUNAR_RELATION" ("EQ_EV_YR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_IX" ;
--------------------------------------------------------
--  Constraints for Table LUNAR_RELATION
--------------------------------------------------------

  ALTER TABLE "QUAKE"."LUNAR_RELATION" ADD CONSTRAINT "LUNAR_REL_PK" PRIMARY KEY ("REL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EQ_IX"  ENABLE;
